config/routes.rb
Reviews::Application.routes.draw do
  resources :books do
  end
   get '/about' => 'books#about'

  root 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  mount_uploader :cover, CoverUploader
  self.per_page = 5

  def self.search(search)
    if search
      find(:all, :conditions => ["title LIKE ? OR author LIKE ? OR reviewer LIKE ?","%#{search}%","%#{search}%","%#{search}%"])
    else
      find(:all)
    end
  end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
@books = Book.paginate(:page => params[:page]).search(params[:search])
  end

  # GET /about
  def about
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  def search
    @books = Book.search(params[:title])
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render action: 'show', status: :created, location: @book }
      else
        format.html { render action: 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:author, :title, :review, :reviewer, :cover, :remove_cover, :cover_cache, :remote_cover_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_books.html.haml
- books.each do |book|
  .book
    = image_tag(book.cover_url(:thumb)) if book.cover?
    %p= book.title.truncate(45, separator: ' ')
    %p= book.author.truncate(45, separator: ' ')
    %p= book.review.truncate(150, separator: ' ')
    %p= book.reviewer.truncate(45, separator: ' ')

    .book-actions
      = link_to 'Show', book
      = link_to 'Edit', edit_book_path(book)
      = link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?'}

app/views/books/_form.html.haml
= simple_form_for(@book) do |f|
  = f.error_notification

  .control-group.string.optional
    .controls
    - if @book.cover?
      = image_tag @book.cover_url(:thumb)


  .form-inputs
    = f.input :cover, label: "Upload file from your disk", as: :file
    = f.hidden_field :cover_cache
    = f.input :remote_cover_url, label: "or via url from Internet"
  .form-inputs
    = f.input :author
    = f.input :title 
    = f.input :review
    = f.input :reviewer

  .form-actions
    = f.button :submit

app/views/books/about.html.haml
#about-page

  %h2 My first Ruby on Rails project

  %p This website is made with huge pleasure for Network Architecture classes.

  %br
  %h3 I used following gems:
  .content-center
    %ul
      %li carrierwave - for uploading books' covers
      %li simple_form - for creating forms
      %li less-rails - I'm just preferring less than scss
      %li twitter-bootstrap-rails - views
      %li navigasmic - for menu generation
      %li cloudinary - for storing images in cloud
      %li will_paginate - for pagination
      %li haml-rails - HAML looks better than .erb

  %p Feel free to write to me: anaksamea@gmail.com

app/views/books/edit.html.haml
%h1 Editing review


.links
  .btn.btn-info= link_to 'Go back', books_path


= render 'form'

app/views/books/index.html.haml
= javascript_include_tag "jquery"
= javascript_include_tag "jquery.inview.min"
= javascript_include_tag "book.js"

%h1 Books' reviews

#books-container
  = render :partial => 'books', :locals => { :books => @books }
= link_to '>>>Load More Books<<<', books_path(:page => @books.next_page), :class => 'load-more-reviews', :remote => true if @books.next_page

app/views/books/index.js.haml
$('#books-container').append('#{escape_javascript(render partial: "books", :locals => { :books => @books })}');
$('a.load-more-reviews').attr('href', '#{books_path page: @books.next_page}');
 
- unless @books.next_page
  $('a.load-more-reviews').remove();

app/views/books/new.html.haml
%h1 New book

= render 'form'

.links
  .btn.btn-info= link_to 'Back', books_path, :method => "get"

app/views/books/show.html.haml
%p{ :id => notice}= notice
.content-center
  .cover
    = image_tag @book.cover_url if @book.cover?

  %br
  %p Author: #{@book.author}

  %p Title:  #{@book.title}

  %p 
    Review: #{@book.review}

  %p
    Reviewer: #{@book.reviewer}
  
  .links
    .btn.btn-info
      = link_to 'Edit', edit_book_path(@book)
    .btn.btn-info
      = link_to 'Back', books_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title>Reviews
  = stylesheet_link_tag    "application", media: "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
  %body
    .navbar
      .navbar-inner
        %a.brand{ :href => "/"} MENU
        = semantic_navigation :primary, config: :bootstrap
        %form.navbar-form.navbar-right{ :role => "form"}
          .form-group
            = form_tag books_path, :method => 'get' do
              = text_field_tag :search, params[:search], class:'form-control'
              = submit_tag "Szukaj", class:'btn btn-success' , :name => nil, :onclick => "$( document ).ready($('a.load-more-reviews').remove());"
    .content
      .row  
        = yield
        #footer
          %p Made by Marta Buda